---
# Edit /etc/hosts

- name: insert and append hostname + ip
  lineinfile:
    path: /etc/hosts
    regexp: '^45\.142\.114\.137'
    line: 45.142.114.137  server01.alpha-itservice.de


- name: insert and append hostname + ip 2
  lineinfile:
    path: /etc/hosts
    regexp: '^45\.142\.114\.137'
    insertafter: '^45\.142\.114\.137'
    line: 45.142.114.140  server01.us72.de
