---
# Edit /etc/hosts

- name: insert and append hostname + ip
  lineinfile:
    path: /etc/hosts
    regexp: '^45\.142\.114\.137'
    line: 45.142.114.137  server01.alpha-itservice.de


- name: insert and append hostname + ip 2
  lineinfile:
    path: /etc/hosts
    insertafter: '^45\.142\.114\.137'
    line: 45.142.114.140  server01.us72.de

- name: insert and append hostname + ip 2
  lineinfile:
    path: /etc/hostname
    regexp: '^kvm'
    line: server01.alpha-itservice.de

- name: ouptut files
  command: less /etc/hosts
  register: output1

- name: "Output script"
  debug:
    msg: "{{ output1.stdout | to_yaml }}"

- name: output files 2
  command: less /etc/hostname
  register: output2

- name: "Output script"
  debug:
    msg: "{{ output2.stdout | to_yaml }}"
