---
# install packages
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Install a list of packages
  apt:
    pkg:
    - vim
    - tmux
    - atop
    - htop
    - man-db
    - manpages-de
