---

# kv#608 hosts modifys
- hosts: kvm608
  gather_facts: false
  remote_user: root
  become: true
  tasks:
    - include_role:
        name: host-file
    - include_role:
        name: install Packages
    - include_role:
        name: install_and_configure_ufw
